# Generated by Django 4.2.6 on 2023-10-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventbooking_is_approved_venuebooking_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='venuebooking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
