# Generated by Django 4.2.6 on 2023-10-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_contacts_event_end_time_event_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='contacts',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='map_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
