# Generated by Django 4.2.6 on 2023-10-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_venue_contacts_venue_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuebooking',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
