# Generated by Django 4.2.6 on 2023-10-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_user_venue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pay_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='pay_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
