# Generated by Django 4.2.6 on 2023-10-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_pay_number_venue_pay_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('BIRTHDAY', 'BIRTHDAY'), ('WEDDING', 'WEDDING'), ('ANNIVERSARY', 'ANNIVERSARY'), ('GRADUATION', 'GRADUATION'), ('SMALL PART', 'SMALL PART'), ('ADVENTURE', 'ADVENTURE')], max_length=200, null=True),
        ),
    ]
